### ISSUE TITLE
测试用例报错

### ISSUE THREAD

**Issue by willhuo** [steponteam/FaceRecognization#9]
堆栈信息如下
   at Stepon.FaceRecognization.Detection.Wrapper.DetectionWrapper.AFD_FSDK_InitialFaceEngine(String appId, String sdkKey, Byte[] memory, Int32 memroySize, IntPtr& engine, Int32 orientPriority, Int32 scale, Int32 maxFaceNumber)
   at Stepon.FaceRecognization.Detection.FaceDetection.Initialize(OrientPriority orientPriority, Int32 scale, Int32 maxFaceNumber) in C:\Users\SDD1\Desktop\FaceRecognization-master\Stepon.FaceRecognization\Stepon.FaceRecognization\Detection\FaceDetection.cs:line 74
   at Stepon.FaceRecognization.Common.LocatorFactory.GetLocator(String appId, String sdkKey, Boolean useTracking, Int32 preAllocMemSize, OrientPriority orientPriority, Int32 scale, Int32 maxFaceNumber) in C:\Users\SDD1\Desktop\FaceRecognization-master\Stepon.FaceRecognization\Stepon.FaceRecognization\Common\LocatorFactory.cs:line 123
   at Stepon.FaceRecognization.Common.LocatorFactory.GetDetectionLocator(String appId, String sdkKey, Int32 preAllocMemSize, OrientPriority orientPriority, Int32 scale, Int32 maxFaceNumber) in C:\Users\SDD1\Desktop\FaceRecognization-master\Stepon.FaceRecognization\Stepon.FaceRecognization\Common\LocatorFactory.cs:line 30
   at Tests.Program.TestDetection() in C:\Users\SDD1\Desktop\FaceRecognization-master\Stepon.FaceRecognization\Tests\Program.cs:line 143
   at Tests.Program.Main(String[] args) in C:\Users\SDD1\Desktop\FaceRecognization-master\Stepon.FaceRecognization\Tests\Program.cs:line 16

貌似也没法贴图，执行的Stepon.FaceRecognization解决方案下的Test项目，方法是TestDetection
但是我用nuget包测试的时候，没有出错，直接执行master的代码，出错

**Comment by willhuo** [comment]
还有就是我修改了一些方法，将版本降到了netframework4.0

**Comment by willhuo** [comment]
经过反复的测试，降低到net4.0版本后的工具包Stepon.FaceRecognization，如果用net4.5.1的测试项目Test调用，会显示正常。如果全部更换成net4.0以后，就会出现异常情况，就是上边的那个堆栈信息。

后来我无意中想起来，这个虹软科技的人脸识别SDK是区分X86和X64之分的，测试项目中，我一直没有注意这个问题。后来我改成X86编译后，就通过了。

可能我比较SB，这个问题处理了一下午，到现在才搞定。。。。哎。。。。
